name: No Deploy (Test and Build)

on:
  # Run on any push to any branch except master
  push:
    branches-ignore: [master]

  # Run on any pull request targeting master
  pull_request:
    branches: [master]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Lint
      run: pnpm run lint
    - name: Deep Type check
      run: pnpm run type-check
    - name: Build application
      run: pnpm run build
